services:
  - type: web
    name: gatorswamp
    env: go
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../backend && go build -o gatorswamp
    startCommand: cd backend && ./gatorswamp
    envVars:
      - key: PORT
        value: 5500
      - key: DB_NAME
        value: Gator-Homes
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true 